name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter:
  flutter_bloc: ^8.1.3  
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Poppins
  #     fonts: 
  #       - asset: assets/fonts
